// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVX96PA0TTGmvCUl78Mqn4ezqwpgGwcgI',
    appId: '1:73270278385:web:0cab5d4594a6ad219d1150',
    messagingSenderId: '73270278385',
    projectId: 'chatapp-c6652',
    authDomain: 'chatapp-c6652.firebaseapp.com',
    storageBucket: 'chatapp-c6652.firebasestorage.app',
    measurementId: 'G-MD6VP39E5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQgZJu8lIvbNwiHMbmTmEi3D4De8d5BxU',
    appId: '1:73270278385:android:ee120441107283079d1150',
    messagingSenderId: '73270278385',
    projectId: 'chatapp-c6652',
    storageBucket: 'chatapp-c6652.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1O9SCMwgyngPjv-Z5tGBB948PFDLKYPk',
    appId: '1:73270278385:ios:6248b05ba2b06b769d1150',
    messagingSenderId: '73270278385',
    projectId: 'chatapp-c6652',
    storageBucket: 'chatapp-c6652.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1O9SCMwgyngPjv-Z5tGBB948PFDLKYPk',
    appId: '1:73270278385:ios:6248b05ba2b06b769d1150',
    messagingSenderId: '73270278385',
    projectId: 'chatapp-c6652',
    storageBucket: 'chatapp-c6652.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVX96PA0TTGmvCUl78Mqn4ezqwpgGwcgI',
    appId: '1:73270278385:web:92f0b51da59bc05a9d1150',
    messagingSenderId: '73270278385',
    projectId: 'chatapp-c6652',
    authDomain: 'chatapp-c6652.firebaseapp.com',
    storageBucket: 'chatapp-c6652.firebasestorage.app',
    measurementId: 'G-TMHVM010S8',
  );
}
